trigger:
 branches:
  include:
    - main
 paths:
   exclude:
     - pipelines

name: Deploy Core Bicep files - $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)   

variables:
  vmImageName: 'ubuntu-latest'
  devAzureServiceConnection: 'russ-airs'
  testAzureServiceConnection: 'russ-airs'
  prodAzureServiceConnection: 'russ-airs'
  location: 'uksouth'
  resourceGroupName: 'rg-devops-automate'


stages:
- stage: 'dev_deploy'
  displayName: 'Deploy to Dev Environment Stage'
  jobs:
  - deployment: 'dev_deploy_bicep'
    displayName: 'Deploy to Dev Environment Deployment'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(devAzureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                ls -R
                az --version
                cd bicep
                az group create --name $(resourceGroupName) --location $(location)
                az deployment group create --name kvdeploy -g $(resourceGroupName) --template-file keyvault.bicep --parameters @keyvault.parameters.json
                az deployment group create --name fnappdeploy -g $(resourceGroupName) --template-file fnapp.bicep
                az deployment group create --name apiconndeploy -g $(resourceGroupName) --template-file apiconnections.bicep

                 